# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHeaderView, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QStatusBar, QTreeView, QWidget)
import rc_icons

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(796, 660)
        MainWindow.setTabletTracking(False)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionAbout_Qt = QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(u"actionAbout_Qt")
        self.actionRename = QAction(MainWindow)
        self.actionRename.setObjectName(u"actionRename")
        self.actionMake_folder = QAction(MainWindow)
        self.actionMake_folder.setObjectName(u"actionMake_folder")
        self.actionDelete_folder = QAction(MainWindow)
        self.actionDelete_folder.setObjectName(u"actionDelete_folder")
        self.actionNew_File = QAction(MainWindow)
        self.actionNew_File.setObjectName(u"actionNew_File")
        self.actionMove = QAction(MainWindow)
        self.actionMove.setObjectName(u"actionMove")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.cope_btn = QPushButton(self.centralwidget)
        self.cope_btn.setObjectName(u"cope_btn")
        self.cope_btn.setGeometry(QRect(10, 10, 60, 60))
        icon = QIcon()
        icon.addFile(u":/imgs_file_manager/copy-alt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cope_btn.setIcon(icon)
        self.cope_btn.setIconSize(QSize(40, 40))
        self.cut_btn = QPushButton(self.centralwidget)
        self.cut_btn.setObjectName(u"cut_btn")
        self.cut_btn.setGeometry(QRect(90, 10, 60, 60))
        icon1 = QIcon()
        icon1.addFile(u":/imgs_file_manager/scissors.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cut_btn.setIcon(icon1)
        self.cut_btn.setIconSize(QSize(40, 40))
        self.paste_btn = QPushButton(self.centralwidget)
        self.paste_btn.setObjectName(u"paste_btn")
        self.paste_btn.setGeometry(QRect(170, 10, 60, 60))
        icon2 = QIcon()
        icon2.addFile(u":/imgs_file_manager/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.paste_btn.setIcon(icon2)
        self.paste_btn.setIconSize(QSize(40, 40))
        self.newFile_btn = QPushButton(self.centralwidget)
        self.newFile_btn.setObjectName(u"newFile_btn")
        self.newFile_btn.setGeometry(QRect(250, 10, 60, 60))
        icon3 = QIcon()
        icon3.addFile(u":/imgs_file_manager/add-document.png", QSize(), QIcon.Normal, QIcon.Off)
        self.newFile_btn.setIcon(icon3)
        self.newFile_btn.setIconSize(QSize(40, 40))
        self.newFolde_btn = QPushButton(self.centralwidget)
        self.newFolde_btn.setObjectName(u"newFolde_btn")
        self.newFolde_btn.setGeometry(QRect(330, 10, 60, 60))
        icon4 = QIcon()
        icon4.addFile(u":/imgs_file_manager/add-folder.png", QSize(), QIcon.Normal, QIcon.Off)
        self.newFolde_btn.setIcon(icon4)
        self.newFolde_btn.setIconSize(QSize(40, 40))
        self.delete_btn = QPushButton(self.centralwidget)
        self.delete_btn.setObjectName(u"delete_btn")
        self.delete_btn.setGeometry(QRect(410, 10, 60, 60))
        icon5 = QIcon()
        icon5.addFile(u":/imgs_file_manager/trash.png", QSize(), QIcon.Normal, QIcon.Off)
        self.delete_btn.setIcon(icon5)
        self.delete_btn.setIconSize(QSize(40, 40))
        self.undu_btn = QPushButton(self.centralwidget)
        self.undu_btn.setObjectName(u"undu_btn")
        self.undu_btn.setGeometry(QRect(10, 80, 35, 35))
        icon6 = QIcon()
        icon6.addFile(u":/imgs_file_manager/undo-alt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.undu_btn.setIcon(icon6)
        self.undu_btn.setIconSize(QSize(25, 25))
        self.redu_btn = QPushButton(self.centralwidget)
        self.redu_btn.setObjectName(u"redu_btn")
        self.redu_btn.setGeometry(QRect(50, 80, 35, 35))
        icon7 = QIcon()
        icon7.addFile(u":/imgs_file_manager/redo-alt.png", QSize(), QIcon.Normal, QIcon.Off)
        self.redu_btn.setIcon(icon7)
        self.redu_btn.setIconSize(QSize(25, 25))
        self.up_btn = QPushButton(self.centralwidget)
        self.up_btn.setObjectName(u"up_btn")
        self.up_btn.setGeometry(QRect(90, 80, 35, 35))
        icon8 = QIcon()
        icon8.addFile(u":/imgs_file_manager/level-up.png", QSize(), QIcon.Normal, QIcon.Off)
        self.up_btn.setIcon(icon8)
        self.up_btn.setIconSize(QSize(25, 25))
        self.directory = QLabel(self.centralwidget)
        self.directory.setObjectName(u"directory")
        self.directory.setGeometry(QRect(130, 80, 411, 31))
        self.find = QLabel(self.centralwidget)
        self.find.setObjectName(u"find")
        self.find.setGeometry(QRect(550, 80, 241, 31))
        self.treeView = QTreeView(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(10, 120, 781, 401))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 796, 25))
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuEdit.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionCopy)
        self.menuFile.addAction(self.actionPaste)
        self.menuFile.addAction(self.actionCut)
        self.menuFile.addAction(self.actionRename)
        self.menuFile.addAction(self.actionMove)
        self.menuFile.addAction(self.actionMake_folder)
        self.menuFile.addAction(self.actionNew_File)
        self.menuFile.addAction(self.actionDelete_folder)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionAbout_Qt)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionAbout_Qt.setText(QCoreApplication.translate("MainWindow", u"About Qt", None))
        self.actionRename.setText(QCoreApplication.translate("MainWindow", u"Rename", None))
        self.actionMake_folder.setText(QCoreApplication.translate("MainWindow", u"New Folder", None))
        self.actionDelete_folder.setText(QCoreApplication.translate("MainWindow", u"Delete", None))
        self.actionNew_File.setText(QCoreApplication.translate("MainWindow", u"New File", None))
        self.actionMove.setText(QCoreApplication.translate("MainWindow", u"Move", None))
        self.cope_btn.setText("")
        self.cut_btn.setText("")
        self.paste_btn.setText("")
        self.newFile_btn.setText("")
        self.newFolde_btn.setText("")
        self.delete_btn.setText("")
        self.undu_btn.setText("")
        self.redu_btn.setText("")
        self.directory.setText("")
        self.find.setText("")
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
    # retranslateUi

