from modules.dialogs.FileEditor import TextEditorDialog
from modules.dialogs.MessageDialog import MessageDialog
from modules.dialogs.FolderSelectorDialog import FolderSelectorDialog
from modules.dialogs.CipherDialog import EncryptCipherDialog, DecryptCipherDialog
